name: Deploy to EC2

on:
  push:
    branches:
      - main  # o la rama que uses

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy andresito branch to testsito folder
        run: |
          cd /home/ubuntu/basilprediction
          git pull origin main
          npm install
          pm2 restart web